version: '3.8'

services:
  usermanagement:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_management:latest
    container_name: user_management_container
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: flask run --host=0.0.0.0 --port=5001
    restart: always
